// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => ios;

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAIpYVRfhl8Gce1e3XShXkzgeiIjYtAJE',
    appId: '1:712648878209:ios:9d67fdcd3685b37f9e0580',
    messagingSenderId: '712648878209',
    projectId: 'simple-paint-2310',
    storageBucket: 'simple-paint-2310.firebasestorage.app',
    iosBundleId: 'com.example.simplePaint',
  );
}
